specVersion: 1.0.0
name: dapps-staking-indexer
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: Astar Network dapps staking indexing service.
repository: 'https://github.com/AstarNetwork/dapps-staking-idnexer'
schema:
  file: ./schema.graphql
# Astar
network:
  chainId: '0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6'
  endpoint: 'wss://rpc.astar.network'
  # dictionary: 'https://api.subquery.network/sq/subquery/astar-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
# Shiden
# network:
#   chainId: '0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108'
#   endpoint: 'wss://rpc.shiden.astar.network'
#   dictionary: 'https://api.subquery.network/sq/subquery/shiden-dictionary'
#   chaintypes:
#     file: ./dist/chaintypes.js
# Local
# network:
#   chainId: '0x920f5ae6aa81de5f183eb5b9f6a56120c8cf759e4af7bcbe8ac919409d75fcf1'
#   endpoint: 'ws://host.docker.internal:9944'
#   chaintypes:
#     file: ./dist/chaintypes.js
dataSources:
- kind: substrate/FrontierEvm
  # startBlock: 1
  startBlock: 815708 #The first era start
  processor:
    file: ./node_modules/@subql/frontier-evm-processor/dist/bundle.js
  mapping:
    file: ./dist/index.js
    handlers:
      - handler: handleFrontierEvmCall
        kind: substrate/FrontierEvmCall
- kind: substrate/Wasm
  startBlock: 815708
  # startBlock: 1
  processor:
    file: ./node_modules/@subql/substrate-wasm-processor/dist/bundle.js
  mapping:
    file: ./dist/index.js
    handlers:
      - handler: handleWasmCall
        kind: substrate/WasmCall
- kind: substrate/Runtime
  startBlock: 815708 #The first era start.
  # startBlock: 1
  mapping:
    file: ./dist/index.js
    handlers:
      - handler: handleNewContract
        kind: substrate/EventHandler
        filter:
          module: dappsStaking
          method: NewContract
      - handler: handleContractRemoved
        kind: substrate/EventHandler
        filter:
          module: dappsStaking
          method: ContractRemoved
      - handler: handleNewDappStakingEra
        kind: substrate/EventHandler
        filter:
          module: dappsStaking
          method: NewDappStakingEra
      - handler: handleBondAndStake
        kind: substrate/EventHandler
        filter:
          module: dappsStaking
          method: BondAndStake
      - handler: handleUnbondAndUnstake
        kind: substrate/EventHandler
        filter:
          module: dappsStaking
          method: UnbondAndUnstake
      - handler: handleWithdrawal
        kind: substrate/EventHandler
        filter:
          module: dappsStaking
          method: Withdrawn
      - handler: handleWithdrawalFromUnregistered
        kind: substrate/EventHandler
        filter:
          module: dappsStaking
          method: WithdrawFromUnregistered
      - handler: handleNominationTransfer
        kind: substrate/EventHandler
        filter:
          module: dappsStaking
          method: NominationTransfer
